[package]
name = "bca-rust"
version = "0.1.0"
authors = ["winwisely268 <winwisely268@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "^0.3"
anyhow = "^1.0"
scraper = "^0.12"
http = "^0.2"

[dependencies.reqwest]
version = "^0.10"
features = ["cookies"]

[dependencies.tokio]
version = "^0.2"
features = ["full"]
